server:
  port: 80
spring:
  datasource:
    hikari:
      username: root
      password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-boot-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
jwt:
  config:
    key: genius
    ttl: 600000
    remember: 604800000